### ISSUE TITLE
"Grid of Posts, classified as" Range Control Moves Both Range Limits at Once

### ISSUE THREAD

**Issue by jchapin** [aurovrata/ReOrder-posts-within-categories#10]
Browser: Safari Version 13.0.2 (15608.2.30.1.1)

Steps to Reproduce:

1. Under the "Posts" menu go to Reorder plugin's section. (/wp-admin/edit.php?page=re-orderPost-post)
1. Select a category to reorder.
1. The category selected in this case has a few hundred post records. In this case, we're looking for a recently written post that's going to show up at the end of the list.
1. When one attempts to drag the user interface control on the right side of the range definition, the left boundary control removes as well.
    1. The expectation is that one would be able to move each of these range limitations independently
    1. If the intention is for the left boundary to move, should it move at the same rate as the right boundary control?
1. There is a workaround for this issue that one can use the input above to type in a number for the number of posts to display on the reordering screen. The only issue with this is that the user may not know how many posts they have in the category, making the draggable UI limitation a better option.

Screenshots of behavior:

Original Position:

<img width="1058" alt="Screen Shot 2019-10-29 at 10 13 35 PM" src="https://user-images.githubusercontent.com/116142/67823999-803f0780-fa9b-11e9-87d5-c1ae99889675.png">

Dragging the upper limit to the right:

<img width="1070" alt="Screen Shot 2019-10-29 at 10 13 49 PM" src="https://user-images.githubusercontent.com/116142/67824001-803f0780-fa9b-11e9-9425-e08480d249b6.png">

Dragging the upper limit further to the right.

<img width="1063" alt="Screen Shot 2019-10-29 at 10 14 01 PM" src="https://user-images.githubusercontent.com/116142/67824002-803f0780-fa9b-11e9-8ded-7653d0d22b13.png">

**Comment by aurovrata** [comment]
the controls move when the limit of posts to display is reached.

This to reduce the load on the server.  WP limits REST api posts to 100, and this is the base value used.  However, the plugin uses a dynamic approach, based on a grid square, hence when your posts  grid number of columns equated the number of rows, the slider will automatically adjust the non-dragged slider button to maintain that square.

If you wish to display more posts, reduce your window zoom level (ctrl+mouse scroll on firefox/chrome, now sure on safari), this will force the number of columns to expand and therefore the js script will allow more posts to be loaded until the rows match the columns.

**Comment by aurovrata** [comment]
Since I have not heard back from you on this, I am assume that it is no longer a problem and tehrefore closing this issue.
