### ISSUE TITLE
Not authorized to access page

### ISSUE THREAD

**Issue by Freundschaft** [aurovrata/ReOrder-posts-within-categories#14]
Hi there, I just installed the plugin, but when I try to go to the settings page to configure the plugin, I receive an error telling me that I'm not authorized to view the page
the URL is:
/wp-admin/options-general.php?page=reorder-posts-within-categories.php

**Comment by Freundschaft** [comment]
I just figured out that when I go to the settings page manually, it works, but apparently it fails only when accessing it directly from the notification after installation

**Comment by aurovrata** [comment]
ok, thanks for reporting this.

Fixed in v2.5.8
