### ISSUE TITLE
How to adjust admin UI?

### ISSUE THREAD

**Issue by minimedj** [aurovrata/ReOrder-posts-within-categories#20]
Hi guys! I want to have sorting admin looks like below:

![screenshot-1](https://user-images.githubusercontent.com/3855032/120678720-afe49b80-c498-11eb-93f3-e15cf6ac6668.png)

How would I implement it? I checked code, but I don't know how to setup JS to show vertical list instead of horizontal. Any advices?

Thank you in advance!

**Comment by aurovrata** [comment]
Please use the WordPress plugin [forum](https://wordpress.org/support/plugin/reorder-post-within-categories/) for support.

The GitHub is only for code development and bug reporting/fixing
