### ISSUE TITLE
Not ordering posts 

### ISSUE THREAD

**Issue by wabj** [aurovrata/ReOrder-posts-within-categories#23]
Hi, I'm using the latest version of this plugin, but it doesn't seem to be working, I drag and drop posts in the order I'd like, visit the front end and nothing changes.

When I go back to the drag and drop page it refreshes and resets the order. I can't work out what is happening.

I get the following error:

WordPress database error: [You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'UNIQUE rpwc_pm.post_id FROM 41_postmeta as rpwc_pm, 41_posts as rpwc_p ...' at line 1]
SELECT UNIQUE rpwc_pm.post_id FROM 41_postmeta as rpwc_pm, 41_posts as rpwc_p WHERE rpwc_pm.meta_key ='_rpwc2' AND rpwc_pm.meta_value=15 AND rpwc_pm.post_id=rpwc_p.ID AND rpwc_p.post_type='portfolio' ORDER BY rpwc_pm.meta_id

**Comment by aurovrata** [comment]
please use the plugin forum for support.  The github repo is specifically for discussing code issues and PRs

**Comment by aurovrata** [comment]
v2.10.4 should fix this.
