### ISSUE TITLE
ReOrder not working with WordPress 5.9

### ISSUE THREAD

**Issue by KendallRogersD1** [aurovrata/ReOrder-posts-within-categories#24]
Just an FYI -- it's not working with 5.9. Might need a little patch?

thanks gang! love the plugin.

**Comment by aurovrata** [comment]
ok thanks for the headsup, will take a look this comgin w.e.

are you able to spot any errors (PHP/JS) ?

**Comment by aurovrata** [comment]
works fine on my server.

If you have issue please use the WordPress support forum.  The GitHub repo is for confirmed bugs/code review.
