### ISSUE TITLE
Filter function get_thumbnail_url

### ISSUE THREAD

**Issue by kpanosgr** [aurovrata/ReOrder-posts-within-categories#28]
Hello there, thank you for the wonderful plugin. 

So this is not an issue, rather a suggestion for the next release. We use acf to our posts, not the default wp attachment image. It would be nice to add a filter in function get_thumbnail_url (file class-reorder-post-within-categories-admin.php) to return the url of a custom field image. 

Thank you for your consideration.

**Comment by aurovrata** [comment]
done.  The function will now return,

```php
return apply_filters( 'rpwc2_get_thumbnail_url', $img, $post->ID )
```
this will come out in v2.15.0

In the meantime you can manually upgrade to [v2.15.0rc1](https://github.com/aurovrata/ReOrder-posts-within-categories/releases/tag/v2.15.0rc1) and let me know if it fulfils your needs.

**Comment by kpanosgr** [comment]
excellent!!!
