### ISSUE TITLE
In some case all the posts for a category in the "reorder_post_rel" are deleted

### ISSUE THREAD

**Issue by guicara** [aurovrata/ReOrder-posts-within-categories#5]
Hello,

First of all, thank you for this plugin!

I reorder posts within a category where posts are often deleted or reassigned to other categories.

I don't know exactly why, but in some case all the posts for a given category in the `reorder_post_rel` table are deleted. As a consequence, the database query returns no posts. I was not able to determine where the bug is.

To fix this bug, I had to check in the `posts_join`, `posts_where` and `posts_orderby` filters, if the `reorder_post_rel` table, for the given category ID, contains entries. If yes, we can safely alter the wp_query object.

```
/**
 * Make sure that the reorder table is not empty for this given category!
 * It there is not entry, we do not want to alter the WP Query (it will returns no posts in the loop).
 *
 * @param int $idCategory The category ID
 * @return bool
 */
private function isPostsOrderedInCategory($idCategory)
{
    global $wpdb;

    $table_name = $wpdb->prefix . $this->deefuse_ReOrder_tableName;

    $nbPosts = $wpdb->get_var($wpdb->prepare("SELECT COUNT(*) FROM $table_name WHERE category_id=%d", $idCategory));

    return ($nbPosts > 0);
}


public function reOrder_query_join($args, $wp_query)
{
    // ...

    $userOrderOptionSetting = $this->getOrderedCategoriesOptions();
    if (!empty($userOrderOptionSetting[$theID]) && $userOrderOptionSetting[$theID] == "true" && $this->stop_join == false) {
        if ($this->isPostsOrderedInCategory($theID)) {
            $args .= " INNER JOIN $table_name ON " . $wpdb->posts . ".ID = " . $table_name . ".post_id and incl = 1  ";
            //echo $args;
        }
    }

    return $args;
}

public function reOrder_query_where($args, $wp_query)
{
    // ...

    $userOrderOptionSetting = $this->getOrderedCategoriesOptions();
    if (!empty($userOrderOptionSetting[$theID]) && $userOrderOptionSetting[$theID] == "true" && $this->stop_join == false) {
        if ($this->isPostsOrderedInCategory($theID)) {
            //$args .= " INNER JOIN $table_name ON ".$wpdb->posts.".ID = ".$table_name.".post_id and incl = 1  ";
            $args .= " AND $table_name" . ".category_id = '" . $theID . "'";
            //echo $args;
        }
    }

    return $args;
}

public function reOrder_query_orderby($args, $wp_query)
{
    // ...

    $userOrderOptionSetting = $this->getOrderedCategoriesOptions();
    if (!empty($userOrderOptionSetting[$theID]) && $userOrderOptionSetting[$theID] == "true" && $this->stop_join == false) {
        if ($this->isPostsOrderedInCategory($theID)) {
            $args = $table_name . ".id ASC";
        }
    }

    return $args;
}
```

I hope it helps!

Guillaume

**Comment by aurovrata** [comment]
Hello Guillaume I realise I never saw this post of yours.  Apologies for such a late reply.  

I am not sure what is the problem.  I have never see this error before.  Is this still an issue?

**Comment by aurovrata** [comment]
Please note that with v2.x the custom table reorder_post_rel is not longer being used as all ranking details have been moved to posts metas.  This enables post types to have ranking orders for the same taxonomy term (some settups have the same taxonomy used across several post types).

So quite a lot has changed and since this issue is realted to the 1.x plugin version I am now closing this as it is no longer being maintained.
