### ISSUE TITLE
When this plugin is activated, my Divi filterable portfolio doesn´t work

### ISSUE THREAD

**Issue by mscembo** [aurovrata/ReOrder-posts-within-categories#6]
Hi. This is an awesome plugin to show the filterable portfolio using Project Type Post. This is exactly what I need to reorder project portfolios, because currently my portfolio shows the posts order By date and I can not find any way to change it by "Alphabetical order". Therefore, when I activate this plugin, I have the ability to order my posts by alphabet order, within the category (EXCELLENT!), But, in the front-end, the Portfolio does not show any project. My Theme is Divi, and my filterable portfolio should be displayed in: (ReOrder-posts-within-categories deactivated, of course).
http://sociedadvenezolanacirugiaplastica.org/zona-de-miembros/directorio-por-apellidos/

When I activate the plugin, the Filterable Portfolio only shows categories A, B, C, D, E ... squares, but none of theme displays de respective category. 

Thank you in advance, I apreciate your work!

Regards,

María Cemborain
![captura de pantalla 2018-08-04 a las 3 50 48 a m](https://user-images.githubusercontent.com/42086649/43673972-d77e65d8-9799-11e8-8f48-94e8884b2365.png)
![captura de pantalla 2018-08-04 a las 3 52 18 a m](https://user-images.githubusercontent.com/42086649/43673973-d7a52844-9799-11e8-8c59-daae23afadfb.png)

**Comment by aurovrata** [comment]
Please use the [WordPress support forum](https://wordpress.org/support/plugin/reorder-post-within-categories) for plugin support.  The GitHub repo is only for PR and code-specific issues.
