### ISSUE TITLE
Filter 'reorder_post_within_category_query_args' disappeared in v2?

### ISSUE THREAD

**Issue by fofoy** [aurovrata/ReOrder-posts-within-categories#9]

**Comment by aurovrata** [comment]
yes, it did.  Apologies if you were using it and it broke your site on upgrade.

I have replaced it with a simpler approach for intial-order load of a new category.  More details in the [plugin page FAQ](https://wordpress.org/plugins/reorder-post-within-categories/#faq) 5 and 7.
